"""The assertion functions, grouped, and the registry that names them.

ASSERTIONS is the only place a case name is bound to the function that
judges it: the suite runs what this dict lists and nothing else, so a case
file missing from here is dead weight -- suite_integrity in runtests.py
refuses to start the run when the two disagree.
"""

from suite.assertions.examples import (  # noqa: F401
    a_clash_input,
    a_customise,
    a_exlbr,
    a_exsource,
    a_numbering,
    a_option_unknown,
    a_termination,
    a_verb,
    a_zpop,
)
from suite.assertions.judgments import (  # noqa: F401
    a_judgment_align,
    a_judgments,
    a_parens_glossing_align,
    a_phantomalign,
    a_phantommarks,
    a_phantommarks_tagged,
)
from suite.assertions.glossing import (  # noqa: F401
    a_babel_de,
    a_babel_fr,
    a_babel_fr_order,
    a_cedilla,
    a_cedilla_gb4e,
    a_cedilla_internal,
    a_gloss,
    a_glt,
    a_glt_side,
    a_utf8,
    a_utf8_unicode,
)
from suite.assertions.alternatives import (  # noqa: F401
    a_altg,
    a_altg_phantomalign,
    a_altkids,
    a_altn,
    a_altn_phantomalign,
    a_altspoken,
    a_alttuck,
)
from suite.assertions.refs import (  # noqa: F401
    a_cleveref,
    a_cleveref_named,
    a_hypanchors,
    a_refs,
    a_relreflinks,
    a_relreflinks_beamer,
    a_relreflinks_beamer_reset,
    a_relreflinks_off,
    a_relreflinks_reset,
    a_relrefs,
)
from suite.assertions.tagging import (  # noqa: F401
    a_exannot,
    a_exannot_beamer,
    a_exannot_fit,
    a_exannot_fitbody,
    a_exannot_ua,
    a_frontend,
    a_lpzg_mod,
    a_lpzgcheck,
    a_lpzglist,
    a_lpzgsetup,
    a_tagged,
    a_ua,
)
from suite.assertions.langsci import (  # noqa: F401
    a_gbfour,
    a_langsci,
    a_langsci_ellipsis,
    a_langsci_exewidth,
    a_langsci_extra,
    a_langsci_hole,
    a_langsci_lists,
    a_langsci_mixed,
    a_langsci_names,
    a_langsci_options,
    a_langsci_refs,
    a_langsci_ua,
    a_legacy,
    a_legacy_gb4e,
)

ASSERTIONS = {
    "customise": a_customise,
    "cleveref": a_cleveref,
    "cleveref-named": a_cleveref_named,
    "hypanchors": a_hypanchors,
    "cedilla": a_cedilla,
    "cedilla-gb4e": a_cedilla_gb4e,
    "cedilla-internal": a_cedilla_internal,
    "legacy": a_legacy,
    "legacy-gb4e": a_legacy_gb4e,
    "tagged": a_tagged,
    "frontend": a_frontend,
    "ua": a_ua,
    "utf8": a_utf8,
    "utf8-unicode": a_utf8_unicode,
    "gbfour": a_gbfour,
    "langsci": a_langsci,
    "langsci-mixed": a_langsci_mixed,
    "langsci-ua": a_langsci_ua,
    "langsci-lists": a_langsci_lists,
    "langsci-names": a_langsci_names,
    "langsci-refs": a_langsci_refs,
    "langsci-hole": a_langsci_hole,
    "langsci-extra": a_langsci_extra,
    "langsci-ellipsis": a_langsci_ellipsis,
    "langsci-exewidth": a_langsci_exewidth,
    "langsci-options": a_langsci_options,
    "numbering": a_numbering,
    "judgment-align": a_judgment_align,
    "judgments": a_judgments,
    "exsource": a_exsource,
    "exannot": a_exannot,
    "exannot-ua": a_exannot_ua,
    "exannot-fit": a_exannot_fit,
    "exannot-fitbody": a_exannot_fitbody,
    "exannot-beamer": a_exannot_beamer,
    "glt-side": a_glt_side,
    "zpop": a_zpop,
    "gloss": a_gloss,
    "glt": a_glt,
    "lpzgcheck": a_lpzgcheck,
    "lpzg-mod": a_lpzg_mod,
    "lpzglist": a_lpzglist,
    "lpzgsetup": a_lpzgsetup,
    "phantomalign": a_phantomalign,
    "parens-glossing-align": a_parens_glossing_align,
    "phantommarks": a_phantommarks,
    "phantommarks-tagged": a_phantommarks_tagged,
    "altg": a_altg,
    "altn": a_altn,
    "altspoken": a_altspoken,
    "altkids": a_altkids,
    "altn-phantomalign": a_altn_phantomalign,
    "altg-phantomalign": a_altg_phantomalign,
    "alttuck": a_alttuck,
    "babel-de": a_babel_de,
    "babel-fr": a_babel_fr,
    "babel-fr-order": a_babel_fr_order,
    "termination": a_termination,
    "verb": a_verb,
    "exlbr": a_exlbr,
    "clash-input": a_clash_input,
    "refs": a_refs,
    "relrefs": a_relrefs,
    "relreflinks": a_relreflinks,
    "relreflinks-off": a_relreflinks_off,
    "option-unknown": a_option_unknown,
    "relreflinks-reset": a_relreflinks_reset,
    "relreflinks-beamer": a_relreflinks_beamer,
    "relreflinks-beamer-reset": a_relreflinks_beamer_reset,
}
